title: Dario Tommasini
email: dtommasini@berkeley.edu
description: >-
  Personal website for Dario Tommasini
url: "https://dariotommasini.github.io"  # upgraded to https

# Build settings
remote_theme: jekyll/minima          # <-- key change for v3 on GitHub Pages
minima:
  skin: classic                      # options: classic, dark, auto, solarized, solarized-dark
  date_format: "%B %-d, %Y"
  social_links:
    - { platform: twitter,  user_url: "https://twitter.com/TommasiniDario" }
    - { platform: github,   user_url: "https://github.com/dariotommasini" }
    - { platform: email,    user_url: "mailto:dtommasini@berkeley.edu" }

header_pages:
  - aboutme.markdown
  - research.markdown
  - conferences.markdown
  - collaborators.markdown
  - quotes.markdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme             # required for remote_theme to work on GitHub Pages

